### ISSUE TITLE
Eris Rewrite

### ISSUE THREAD

**Issue by ohlookitsderpy** [discord-emoji/bot#8]
Eris could fix this issue? It'd also make the bot faster.

**Comment by ohlookitsAugust** [comment]
JDA when

**Comment by ohlookitsderpy** [comment]
why do i need JDA there's no music commands :^)

**Comment by ohlookitsderpy** [comment]
also Eris = good sharding

**Comment by ohlookitsAugust** [comment]
jda has gud sharding too. I coded Rem's shard file.

**Comment by ohlookitsAugust** [comment]
if you want :eyes:

**Comment by ohlookitsderpy** [comment]
lol atm i'd rather it be in eris as it will be easier to install on my vps and update

**Comment by ohlookitsAugust** [comment]
ok let's do it

**Comment by ohlookitsderpy** [comment]
new branch?

**Comment by ohlookitsderpy** [comment]
new branch?
